### ISSUE TITLE
I can’t find the music folder from the raspberry

### ISSUE THREAD

**Issue by jonghanson** [fison67/GH-Connector#1]
I can’t find the music folder from the raspberry.
Question. Do i need to add a “yourMp3Folder” from the Docker/Gh-connector/yourMp3Folder/music1 ?????

**Comment by fison67** [comment]
Raspberry pi Music Folder = anything you want folder
Docker Folder = /music1 , /music2, /music3, /music4, /music5 (fixed)

**Comment by jonghanson** [comment]
Unfortunately, I cannot understand what you’re trying to explain. “Anything i want folder means”?? Cuz, I tried to make a folder from Docker/music1/music.mp3 file. Cannot see it from the playlist. I can make googlehome speak to repeat with TTS. But no muisc or any other files.
