### ISSUE TITLE
Is there anyway tonchange the voice to English.

### ISSUE THREAD

**Issue by jonghanson** [fison67/GH-Connector#2]
I was expected with English voice.
But there was only chance i can choose with Korean voices. Is there anyway i can change it to the English voices?

**Comment by fison67** [comment]
You mean oddcast voice type?

**Comment by jonghanson** [comment]
Well, I mean just regular google assistant english voices. Not a Korean voices. I tried several time to change the Korean to English. But there is no clue. For example) English TTS reading by english voices.

**Comment by fison67** [comment]
Set a TTS Language on device settings

**Comment by jonghanson** [comment]
Well, I already tried with language settings. It keep over and over again. I cannot find the English version of google voice. 
Question) Did you add the English version of TTS voices?? or have you try it set the TTS with english before? or Is this connector use it by for only Korean?

IF YOU ALREADY ADD THE ENGLISH VOICES.
Could you tell us any English version of google voices name. 
ex) blue, red, british racing

Cuz, None of them exist at all.

**Comment by fison67** [comment]
![image](https://user-images.githubusercontent.com/2555973/60087118-54231b00-9777-11e9-943b-07dce06b76c7.png)

**Comment by jonghanson** [comment]
en-US - What’s the title of voice name?? (red, blue, green) ??
en-GB - What’s the title of voice name??
So i can set a TTS voice option.

**Comment by fison67** [comment]
I don’t know what you’re saying.

This program doesn’t use same google voice of Google Home Device.

There are 3 type voice.
1. Google
2. Naver
3. Oddcast
If you want use google voice, you just set a en-us. No person to choose google voice type.

**Comment by jonghanson** [comment]
Request for the all the user those who using English TTS. Please, put the “oddcast” you mentioned about list. Add more English version voice or “en-us”, “en-gb” select the name so we can put the value for voice data.

**Comment by jonghanson** [comment]
Perhaps, You could add more “oddcast” for the English version for the those who using english language.

**Comment by jonghanson** [comment]
For the lot more taste. You know what i mean right? We appreciate with you hardwork. But give it a shot. Thanks,

**Comment by jonghanson** [comment]
If you add oddcast for English version of google voice name “Green” it will be much appreciate it.
You can hear the voice from Googlehome App settings for English version only.
