### ISSUE TITLE
포트 및 오타 수정 요청

### ISSUE THREAD

**Issue by wanheecho** [fison67/GH-Connector#3]
아기나무집 님의 gh-connector를 라즈베리에 설치하여 도커에 구동까지는 성공을 하였습니다.

그러나 기본 포트 30010 이라고 가이드에 나오나, 실제 포트 조회를 해보니 43201 로 접속 해야 , 설정 페이지 접근이 가능 하더라고요. 혹시 포트가 바뀐 이유가 있을까요?

포트는 그냥 43201을 사용한다 할지 라도, web 에서 TTS 테스트를 위해 가이드에 나온대로 

http://192.168.0.154:43201/googlehome/192.168.0.149/tts?message=test&lang=ko&volume=20
를 했으나, 응답은 {} <-이렇게 오면서, 구글홈으 아무런 반응이 없더라고요.(가이드의 message부분에 오타가 있습니다)

혹시 제가 잘못하고 있는게 있을까요? 조언 부탁드립니다.

감사합니다

**Comment by fison67** [comment]
포트는 설정 파일 건드리지 않는 이상 30010 이 정상입니다.

api 는 변경 되었으니 참조하시고, message 오타는 수정하였습니다.

감사합니다.
